# Generated by Django 3.1.3 on 2020-12-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201211_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='original_bag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_pid',
        ),
    ]
