# Generated by Django 3.1.3 on 2020-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201206_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
    ]
