# Generated by Django 3.1.3 on 2020-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('sub_categories', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('url1', models.URLField(max_length=1024)),
                ('color1', models.CharField(max_length=254)),
                ('url2', models.URLField(max_length=1024)),
                ('color2', models.CharField(max_length=254)),
                ('url3', models.URLField(max_length=1024)),
                ('color3', models.CharField(max_length=254)),
                ('url4', models.URLField(max_length=1024)),
                ('color4', models.CharField(max_length=254)),
            ],
        ),
    ]
